"""Plain-English definitions behind the ? next to each figure."""

GLOSSARY = {
    "equity": "What the strategy or book is worth now: cash plus open positions marked at the last price.",
    "today": "Change in equity since midnight UTC, after fees.",
    "mtd": "Change in equity since the 1st of this month, after fees.",
    "since_start": "Return since the money was first allocated, after fees. The benchmark is what simply buying the instrument on day one and holding it would have returned.",
    "vs_hold": "The strategy's return minus buy-and-hold over the same period. Positive means the model added value over simply holding the instrument.",
    "in_market": "Gross exposure: the value of open positions as a share of equity. 0% means flat, all cash. In a backtest, the share of time a position was held.",
    "cash": "Uninvested money. Open P&L is the unrealised gain or loss on open positions.",
    "drawdown": "How far equity is below its highest point so far. Measured on every mark, as the risk guard sees it; each risk profile halts a strategy at a set drawdown.",
    "sharpe": "Return per unit of risk: annual return divided by annual volatility. Above 1 is good; buy-and-hold is the bar to beat. Measured on daily closes at every interval, and needs at least 30 days to mean much.",
    "fees": "Venue trading fees paid. Market orders and protective exits pay the taker rate; maker-first orders pay the maker rate on what fills while they rest. The bid-ask spread is shown apart.",
    "volatility": "How much daily returns swing, scaled to a year. Higher means a bumpier ride.",
    "cagr": "Compound annual growth rate: the steady yearly return that would give the same end result.",
    "win_rate": "Share of closed trades that made money after both fees. A low win rate can still be profitable if wins are much bigger than losses.",
    "expectancy": "Average return per closed trade after fees. This is what each new trade is worth on average.",
    "profit_factor": "Money made on winning trades divided by money lost on losing ones. Above 1 is profitable; 1.5 or more is solid.",
    "unrealised": "Gain or loss on open positions, marked at the last price. It becomes realised when sold, and the exit fee is not included yet.",
    "realised": "Profit or loss on closed trades, after entry and exit fees.",
    "exposure_cap": "The most of a strategy's equity its risk profile lets it hold in open positions.",
    "correlation": "Correlation of daily returns. 1 means two strategies move in lockstep, 0 unrelated, below 0 opposite. Low correlation is what spreads risk; darker cells are more alike.",
    "g1": "Gate 1: the strategy beat buy-and-hold out of sample on real data, with enough trades, after fees. Decided by the research loop.",
    "g2": "Gate 2: at least six weeks of paper trading whose results sit inside the backtest's range. Only you can approve it, and only then can a strategy trade real money.",
}
